name: Test Secrets Configuration

on:
  workflow_dispatch:
    inputs:
      test_npm:
        description: 'Test NPM token'
        required: false
        default: 'true'
      test_snyk:
        description: 'Test Snyk token'
        required: false
        default: 'false'

jobs:
  test-secrets:
    name: Test Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test NPM Token
        if: inputs.test_npm == 'true'
        run: |
          if [ -n "${{ secrets.NPM_TOKEN }}" ]; then
            echo "✅ NPM_TOKEN is configured"
            echo "Token length: ${#NPM_TOKEN}"
            echo "Token starts with: ${NPM_TOKEN:0:4}..."
          else
            echo "❌ NPM_TOKEN is not configured"
            exit 1
          fi

      - name: Test Snyk Token
        if: inputs.test_snyk == 'true'
        run: |
          if [ -n "${{ secrets.SNYK_TOKEN }}" ]; then
            echo "✅ SNYK_TOKEN is configured"
            echo "Token length: ${#SNYK_TOKEN}"
          else
            echo "❌ SNYK_TOKEN is not configured"
            exit 1
          fi

      - name: Test Docker Credentials
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "✅ Docker credentials are configured"
            echo "Username: ${{ secrets.DOCKER_USERNAME }}"
          else
            echo "⚠️ Docker credentials are not configured (optional)"
          fi

      - name: Summary
        run: |
          echo "🔐 Secrets Configuration Summary:"
          echo "================================"
          echo "NPM_TOKEN: $([ -n "${{ secrets.NPM_TOKEN }}" ] && echo "✅ Configured" || echo "❌ Missing")"
          echo "SNYK_TOKEN: $([ -n "${{ secrets.SNYK_TOKEN }}" ] && echo "✅ Configured" || echo "⚠️ Optional")"
          echo "DOCKER_USERNAME: $([ -n "${{ secrets.DOCKER_USERNAME }}" ] && echo "✅ Configured" || echo "⚠️ Optional")"
          echo "DOCKER_PASSWORD: $([ -n "${{ secrets.DOCKER_PASSWORD }}" ] && echo "✅ Configured" || echo "⚠️ Optional")"
          echo ""
          echo "🎉 If NPM_TOKEN shows ✅, you're ready to publish packages!"
